import { sql } from "drizzle-orm";
import {
  boolean,
  bigint,
  check,
  date,
  doublePrecision,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

const tenantIdentity = {
  tenantId: uuid("tenant_id").notNull(),
  userId: text("user_id").notNull(),
};

export const productStatusValues = ["draft", "incomplete", "ready", "active", "archived"] as const;
export type ProductStatus = (typeof productStatusValues)[number];

/** Camadas **persistidas** de memória (§15.2 da V7 / §13 do ARQ). L0 (working)
 * fica **fora**: não é persistido, então não há linha para expirar (H-12). */
export const memoryLayerValues = ["L1", "L2", "L3", "L4", "L5"] as const;
export type MemoryLayer = (typeof memoryLayerValues)[number];

/** Ações auditadas em `ai_memory_access_log` (§15.4/D4): retrieval, eliminação
 * e portabilidade. */
export const memoryAccessActionValues = ["access", "delete", "export"] as const;
export type MemoryAccessAction = (typeof memoryAccessActionValues)[number];

/** Resultado de uma operação auditada: `not_found` cobre o id inexistente **e**
 * o de outro tenant (a RLS torna os dois indistinguíveis — não há oráculo de
 * existência) e `refused` é a recusa por política (histórico presente ou
 * memória de escopo pessoal de outro autor). */
export const memoryAccessResultValues = ["allowed", "not_found", "refused"] as const;
export type MemoryAccessResult = (typeof memoryAccessResultValues)[number];

const money = (name: string) => numeric(name, { precision: 19, scale: 4 });
const quantity = (name: string) => numeric(name, { precision: 24, scale: 6 });
const percent = (name: string) => numeric(name, { precision: 9, scale: 6 });

// Better Auth models. String identifiers intentionally preserve imported Supabase UUIDs.
export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: text("image"),
    ...timestamps,
  },
  (table) => [uniqueIndex("users_email_uidx").on(sql`lower(${table.email})`)],
);

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    token: text("token").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("sessions_token_uidx").on(table.token),
    index("sessions_user_id_idx").on(table.userId),
    index("sessions_expires_at_idx").on(table.expiresAt),
  ],
);

export const accounts = pgTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    issuer: text("issuer"),
    password: text("password"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("accounts_provider_account_uidx").on(table.providerId, table.accountId),
    index("accounts_user_id_idx").on(table.userId),
  ],
);

export const verifications = pgTable(
  "verifications",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (table) => [
    index("verifications_identifier_idx").on(table.identifier),
    index("verifications_expires_at_idx").on(table.expiresAt),
  ],
);

/** Better Auth's database-backed rate limiter.  The key is a scoped,
 * non-PII identifier generated by Better Auth; lastRequest is epoch
 * milliseconds as required by its adapter contract. */
// Better Auth's plural adapter mode resolves the `rate_limits` table through
// the `rateLimits` schema key.
export const rateLimits = pgTable(
  "rate_limits",
  {
    id: text("id")
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    key: text("key").notNull(),
    count: integer("count").notNull().default(0),
    lastRequest: bigint("last_request", { mode: "number" }).notNull(),
  },
  (table) => [
    uniqueIndex("rate_limits_key_uidx").on(table.key),
    check("rate_limits_count_check", sql`${table.count} >= 0`),
    index("rate_limits_last_request_idx").on(table.lastRequest),
  ],
);

export const tenants = pgTable(
  "tenants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    kind: text("kind").notNull().default("personal"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("tenants_slug_uidx").on(table.slug),
    check("tenants_kind_check", sql`${table.kind} in ('personal', 'organization')`),
  ],
);

export const tenantMemberships = pgTable(
  "tenant_memberships",
  {
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: text("role").notNull().default("owner"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.userId] }),
    index("tenant_memberships_user_id_idx").on(table.userId),
    check("tenant_memberships_role_check", sql`${table.role} in ('owner', 'admin', 'member')`),
  ],
);

export const profiles = pgTable(
  "profiles",
  {
    id: text("id")
      .primaryKey()
      .references(() => users.id, { onDelete: "cascade" }),
    ...tenantIdentity,
    email: text("email"),
    displayName: text("display_name"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("profiles_tenant_id_id_uidx").on(table.tenantId, table.id),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("cascade"),
    check("profiles_identity_check", sql`${table.id} = ${table.userId}`),
  ],
);

export const products = pgTable(
  "products",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    name: text("name").notNull(),
    status: text("status").$type<ProductStatus>().notNull().default("draft"),
    currentPrice: money("current_price"),
    yieldQty: quantity("yield_qty"),
    yieldUnit: text("yield_unit"),
    taxRegime: text("tax_regime"),
    taxRate: percent("tax_rate"),
    isDemo: boolean("is_demo").notNull().default(false),
    notes: text("notes"),
    version: integer("version").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    unique("products_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("products_tenant_created_idx").on(table.tenantId, table.createdAt),
    index("products_tenant_active_idx").on(table.tenantId, table.archivedAt),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check(
      "products_current_price_check",
      sql`${table.currentPrice} is null or ${table.currentPrice} >= 0`,
    ),
    check("products_yield_qty_check", sql`${table.yieldQty} is null or ${table.yieldQty} > 0`),
    check(
      "products_tax_rate_check",
      sql`${table.taxRate} is null or (${table.taxRate} >= 0 and ${table.taxRate} <= 1)`,
    ),
    check(
      "products_status_check",
      sql`${table.status} in ('draft', 'incomplete', 'ready', 'active', 'archived')`,
    ),
    check("products_version_check", sql`${table.version} >= 0`),
  ],
);

export const productIngredients = pgTable(
  "product_ingredients",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").notNull(),
    ...tenantIdentity,
    name: text("name").notNull(),
    usedQty: quantity("used_qty").notNull(),
    usedUnit: text("used_unit").notNull(),
    packagePrice: money("package_price"),
    packageQty: quantity("package_qty"),
    packageUnit: text("package_unit"),
    conversionFactor: numeric("conversion_factor", { precision: 24, scale: 8 }),
    priceUpdatedAt: timestamp("price_updated_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("product_ingredients_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("product_ingredients_tenant_product_idx").on(table.tenantId, table.productId),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check("product_ingredients_used_qty_check", sql`${table.usedQty} > 0`),
    check(
      "product_ingredients_package_price_check",
      sql`${table.packagePrice} is null or ${table.packagePrice} >= 0`,
    ),
    check(
      "product_ingredients_package_qty_check",
      sql`${table.packageQty} is null or ${table.packageQty} > 0`,
    ),
    check(
      "product_ingredients_conversion_factor_check",
      sql`${table.conversionFactor} is null or ${table.conversionFactor} > 0`,
    ),
  ],
);

export const productPackaging = pgTable(
  "product_packaging",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").notNull(),
    ...tenantIdentity,
    name: text("name").notNull(),
    packagePrice: money("package_price").notNull(),
    unitsPerPackage: quantity("units_per_package").notNull(),
    priceUpdatedAt: timestamp("price_updated_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("product_packaging_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("product_packaging_tenant_product_idx").on(table.tenantId, table.productId),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check("product_packaging_price_check", sql`${table.packagePrice} >= 0`),
    check("product_packaging_units_check", sql`${table.unitsPerPackage} > 0`),
  ],
);

export const salesFees = pgTable(
  "sales_fees",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").notNull(),
    ...tenantIdentity,
    name: text("name").notNull(),
    percentage: percent("percentage").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("sales_fees_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("sales_fees_tenant_product_idx").on(table.tenantId, table.productId),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check(
      "sales_fees_percentage_check",
      sql`${table.percentage} >= 0 and ${table.percentage} <= 1`,
    ),
  ],
);

export const marketPrices = pgTable(
  "market_prices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    productId: uuid("product_id").notNull(),
    ...tenantIdentity,
    minPrice: money("min_price"),
    avgPrice: money("avg_price"),
    maxPrice: money("max_price"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("market_prices_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("market_prices_tenant_product_created_idx").on(
      table.tenantId,
      table.productId,
      table.createdAt,
    ),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check("market_prices_min_check", sql`${table.minPrice} is null or ${table.minPrice} >= 0`),
    check("market_prices_avg_check", sql`${table.avgPrice} is null or ${table.avgPrice} >= 0`),
    check("market_prices_max_check", sql`${table.maxPrice} is null or ${table.maxPrice} >= 0`),
  ],
);

export const expenses = pgTable(
  "expenses",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    name: text("name").notNull(),
    category: text("category"),
    amount: money("amount").notNull(),
    type: text("type").notNull().default("fixa"),
    periodicity: text("periodicity").notNull().default("mensal"),
    isDemo: boolean("is_demo").notNull().default(false),
    notes: text("notes"),
    version: integer("version").notNull().default(0),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("expenses_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("expenses_tenant_created_idx").on(table.tenantId, table.createdAt),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check("expenses_amount_check", sql`${table.amount} >= 0`),
    check("expenses_type_check", sql`${table.type} in ('fixa', 'variavel')`),
    check("expenses_version_check", sql`${table.version} >= 0`),
  ],
);

export const purchasePriceHistory = pgTable(
  "purchase_price_history",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    subjectType: text("subject_type").notNull(),
    subjectId: uuid("subject_id").notNull(),
    // Keep the discriminator during the additive migration for compatibility,
    // while explicit tenant-scoped targets make orphaned history impossible.
    ingredientId: uuid("ingredient_id"),
    packagingId: uuid("packaging_id"),
    price: money("price").notNull(),
    quantity: quantity("quantity").notNull(),
    unit: text("unit").notNull(),
    supplierId: text("supplier_id"),
    validFrom: timestamp("valid_from", { withTimezone: true }).notNull(),
    recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("purchase_price_history_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("purchase_price_history_tenant_subject_valid_idx").on(
      table.tenantId,
      table.subjectType,
      table.subjectId,
      table.validFrom,
    ),
    index("purchase_price_history_tenant_ingredient_valid_idx").on(
      table.tenantId,
      table.ingredientId,
      table.validFrom,
    ),
    index("purchase_price_history_tenant_packaging_valid_idx").on(
      table.tenantId,
      table.packagingId,
      table.validFrom,
    ),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    foreignKey({
      columns: [table.tenantId, table.ingredientId],
      foreignColumns: [productIngredients.tenantId, productIngredients.id],
    }).onDelete("restrict"),
    foreignKey({
      columns: [table.tenantId, table.packagingId],
      foreignColumns: [productPackaging.tenantId, productPackaging.id],
    }).onDelete("restrict"),
    check(
      "purchase_price_history_subject_check",
      sql`${table.subjectType} in ('ingredient', 'packaging')`,
    ),
    check(
      "purchase_price_history_target_check",
      sql`(
        (${table.subjectType} = 'ingredient'
          and ${table.ingredientId} is not null
          and ${table.packagingId} is null
          and ${table.subjectId} = ${table.ingredientId})
        or
        (${table.subjectType} = 'packaging'
          and ${table.ingredientId} is null
          and ${table.packagingId} is not null
          and ${table.subjectId} = ${table.packagingId})
      )`,
    ),
    check("purchase_price_history_price_check", sql`${table.price} >= 0`),
    check("purchase_price_history_quantity_check", sql`${table.quantity} > 0`),
  ],
);

export const sales = pgTable(
  "sales",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
    grossAmount: money("gross_amount").notNull(),
    netAmount: money("net_amount").notNull(),
    channel: text("channel").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("sales_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("sales_tenant_occurred_idx").on(table.tenantId, table.occurredAt),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check("sales_gross_amount_check", sql`${table.grossAmount} >= 0`),
    check(
      "sales_net_amount_check",
      sql`${table.netAmount} >= 0 and ${table.netAmount} <= ${table.grossAmount}`,
    ),
  ],
);

export const salesItems = pgTable(
  "sales_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    saleId: uuid("sale_id").notNull(),
    productId: uuid("product_id").notNull(),
    ...tenantIdentity,
    quantity: quantity("quantity").notNull(),
    unitPrice: money("unit_price").notNull(),
    totalAmount: money("total_amount").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("sales_items_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("sales_items_tenant_sale_idx").on(table.tenantId, table.saleId),
    index("sales_items_tenant_product_idx").on(table.tenantId, table.productId),
    foreignKey({
      columns: [table.tenantId, table.saleId],
      foreignColumns: [sales.tenantId, sales.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("restrict"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check("sales_items_quantity_check", sql`${table.quantity} > 0`),
    check("sales_items_unit_price_check", sql`${table.unitPrice} >= 0`),
    check("sales_items_total_amount_check", sql`${table.totalAmount} >= 0`),
    check(
      "sales_items_total_amount_math_check",
      sql`${table.totalAmount} = round(${table.quantity} * ${table.unitPrice}, 4)`,
    ),
  ],
);

export const simulations = pgTable(
  "simulations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    productId: uuid("product_id"),
    name: text("name").notNull(),
    params: jsonb("params").$type<Record<string, unknown>>().notNull(),
    result: jsonb("result").$type<Record<string, unknown> | null>(),
    scenarioType: text("scenario_type").notNull().default("manual_simulation"),
    engineVersion: text("engine_version").notNull().default("finance-engine/2.0.0"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("simulations_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("simulations_tenant_created_idx").on(table.tenantId, table.createdAt),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("restrict"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check(
      "simulations_scenario_type_check",
      sql`${table.scenarioType} in ('manual_simulation', 'forecast', 'real')`,
    ),
  ],
);

export const calculationSnapshots = pgTable(
  "calculation_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id"),
    calculationType: text("calculation_type").notNull(),
    idempotencyKey: text("idempotency_key")
      .notNull()
      .default(sql`gen_random_uuid()::text`),
    inputs: jsonb("inputs").$type<Record<string, unknown>>().notNull(),
    outputs: jsonb("outputs").$type<Record<string, unknown>>().notNull(),
    engineVersion: text("engine_version").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("calculation_snapshots_tenant_id_id_uidx").on(table.tenantId, table.id),
    uniqueIndex("calculation_snapshots_idempotency_uidx").on(
      table.tenantId,
      table.calculationType,
      table.idempotencyKey,
    ),
    index("calculation_snapshots_tenant_entity_created_idx").on(
      table.tenantId,
      table.entityType,
      table.entityId,
      table.createdAt,
    ),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
  ],
);

export const chatConversations = pgTable(
  "chat_conversations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    currentProductId: uuid("current_product_id"),
    confirmedState: jsonb("confirmed_state").$type<Record<string, unknown>>().notNull().default({}),
    conversationState: text("conversation_state").notNull().default("idle"),
    stateUpdatedAt: timestamp("state_updated_at", { withTimezone: true }).notNull().defaultNow(),
    stateMetadata: jsonb("state_metadata").$type<Record<string, unknown>>(),
    resetAt: timestamp("reset_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("chat_conversations_tenant_user_uidx").on(table.tenantId, table.userId),
    unique("chat_conversations_tenant_id_uidx").on(table.tenantId, table.id),
    check(
      "chat_conversations_state_check",
      sql`${table.conversationState} in ('idle', 'collecting_context', 'calculating', 'confirming', 'executing', 'completed', 'failed')`,
    ),
    foreignKey({
      columns: [table.tenantId, table.currentProductId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("restrict"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("cascade"),
  ],
);

export const chatMessages = pgTable(
  "chat_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    conversationId: uuid("conversation_id").notNull(),
    ...tenantIdentity,
    role: text("role").notNull(),
    content: text("content").notNull(),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("chat_messages_tenant_id_id_uidx").on(table.tenantId, table.id),
    index("chat_messages_tenant_conversation_created_idx").on(
      table.tenantId,
      table.conversationId,
      table.createdAt,
    ),
    foreignKey({
      columns: [table.tenantId, table.conversationId],
      foreignColumns: [chatConversations.tenantId, chatConversations.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("cascade"),
    check(
      "chat_messages_role_check",
      sql`${table.role} in ('user', 'assistant', 'system', 'tool')`,
    ),
  ],
);

export const idempotencyRecords = pgTable(
  "idempotency_records",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    operation: text("operation").notNull(),
    key: text("key").notNull(),
    requestHash: text("request_hash").notNull(),
    status: text("status").notNull().default("pending"),
    response: jsonb("response").$type<Record<string, unknown>>(),
    errorCode: text("error_code"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("idempotency_records_scope_uidx").on(
      table.tenantId,
      table.userId,
      table.operation,
      table.key,
    ),
    index("idempotency_records_expires_idx").on(table.expiresAt),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("cascade"),
    check(
      "idempotency_records_status_check",
      sql`${table.status} in ('pending', 'succeeded', 'failed')`,
    ),
  ],
);

export const toolExecutions = pgTable(
  "tool_executions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    correlationId: uuid("correlation_id").notNull(),
    toolName: text("tool_name").notNull(),
    inputHash: text("input_hash").notNull(),
    status: text("status").notNull().default("pending"),
    durationMs: integer("duration_ms"),
    safeResult: jsonb("safe_result").$type<Record<string, unknown>>(),
    errorCode: text("error_code"),
    idempotencyKey: text("idempotency_key"),
    toolCallId: text("tool_call_id"),
    input: jsonb("input").$type<Record<string, unknown>>(),
    usageId: uuid("usage_id"),
    estimatedCost: money("estimated_cost"),
    costStatus: text("cost_status").notNull().default("unknown"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [
    uniqueIndex("tool_executions_idempotency_uidx").on(
      table.tenantId,
      table.userId,
      table.toolName,
      table.idempotencyKey,
    ),
    index("tool_executions_tenant_started_idx").on(table.tenantId, table.startedAt),
    index("tool_executions_tenant_usage_idx").on(table.tenantId, table.usageId),
    check(
      "tool_executions_cost_status_check",
      sql`${table.costStatus} in ('known', 'unknown', 'invalid')`,
    ),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check(
      "tool_executions_status_check",
      sql`${table.status} in ('pending', 'succeeded', 'failed', 'cancelled')`,
    ),
    check(
      "tool_executions_duration_check",
      sql`${table.durationMs} is null or ${table.durationMs} >= 0`,
    ),
  ],
);

export const aiDailyBudgets = pgTable(
  "ai_daily_budgets",
  {
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    usageDate: date("usage_date").notNull(),
    chatCount: integer("chat_count").notNull().default(0),
    modelCallCount: integer("model_call_count").notNull().default(0),
    toolCallCount: integer("tool_call_count").notNull().default(0),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    tokensReserved: integer("tokens_reserved").notNull().default(0),
    inFlight: integer("in_flight").notNull().default(0),
    estimatedCost: money("estimated_cost").notNull().default("0"),
    estimatedCostUnknownCount: integer("estimated_cost_unknown_count").notNull().default(0),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.usageDate] }),
    check(
      "ai_daily_budgets_nonnegative_check",
      sql`${table.chatCount} >= 0 and ${table.modelCallCount} >= 0 and ${table.toolCallCount} >= 0 and ${table.inputTokens} >= 0 and ${table.outputTokens} >= 0 and ${table.tokensReserved} >= 0 and ${table.inFlight} >= 0 and ${table.estimatedCost} >= 0 and ${table.estimatedCostUnknownCount} >= 0`,
    ),
  ],
);

export const aiUsage = pgTable(
  "ai_usage",
  {
    usageId: uuid("usage_id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    roundNo: integer("round_no").notNull().default(0),
    budgetTokens: integer("budget_tokens").notNull(),
    status: text("status").notNull().default("reserved"),
    reservedAt: timestamp("reserved_at", { withTimezone: true }).notNull().defaultNow(),
    settledAt: timestamp("settled_at", { withTimezone: true }),
    realTokens: integer("real_tokens"),
    outcome: text("outcome"),
    estimatedCost: money("estimated_cost"),
    costStatus: text("cost_status").notNull().default("unknown"),
    toolExecutionId: uuid("tool_execution_id"),
  },
  (table) => [
    index("ai_usage_tenant_status_reserved_idx").on(table.tenantId, table.status, table.reservedAt),
    check("ai_usage_status_check", sql`${table.status} in ('reserved', 'settled', 'expired')`),
    check("ai_usage_round_no_check", sql`${table.roundNo} >= 0`),
    check("ai_usage_budget_tokens_check", sql`${table.budgetTokens} >= 0`),
    check(
      "ai_usage_real_tokens_check",
      sql`${table.realTokens} is null or ${table.realTokens} >= 0`,
    ),
    check(
      "ai_usage_cost_status_check",
      sql`${table.costStatus} in ('known', 'unknown', 'invalid')`,
    ),
  ],
);

export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    correlationId: uuid("correlation_id").notNull(),
    eventType: text("event_type").notNull(),
    resourceType: text("resource_type"),
    resourceId: text("resource_id"),
    safeMetadata: jsonb("safe_metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("audit_events_tenant_created_idx").on(table.tenantId, table.createdAt),
    index("audit_events_correlation_idx").on(table.correlationId),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
  ],
);

/** Série de Web Vitals (RUM) persistida para agregação p75 (§17.8).
 * Sem tenant_id e sem RLS por design: é métrica de performance do browser,
 * sem PII; a ingestão é best-effort (INSERT-only para app_runtime) e a
 * leitura fica restrita ao operador (DATABASE_ADMIN_URL, local-only). */
export const rumVitals = pgTable(
  "rum_vitals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    metricId: text("metric_id").notNull(),
    name: text("name").notNull(),
    value: doublePrecision("value").notNull(),
    rating: text("rating").notNull(),
    delta: doublePrecision("delta").notNull(),
    navigationType: text("navigation_type"),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("rum_vitals_name_received_at_idx").on(table.name, table.receivedAt)],
);

/** §23 — outbox transacional. O evento é inserido na MESMA transação da
 * mutação de domínio (`withTenantTransaction`) e drenado por worker idempotente
 * (23.2). `idempotency_key` é única por tenant: repetir o append devolve o
 * evento existente (`duplicate: true`) em vez de duplicar a linha. */
export const outboxEvents = pgTable(
  "outbox_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    eventType: text("event_type").notNull(),
    aggregateType: text("aggregate_type").notNull(),
    aggregateId: text("aggregate_id").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    status: text("status").notNull().default("pending"),
    attempts: integer("attempts").notNull().default(0),
    /** Próxima tentativa permitida; o backoff de falha empurra este instante. */
    availableAt: timestamp("available_at", { withTimezone: true }).notNull().defaultNow(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
    processedAt: timestamp("processed_at", { withTimezone: true }),
    lastError: text("last_error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("outbox_events_tenant_idempotency_uidx").on(table.tenantId, table.idempotencyKey),
    /** Índice do claim: filtra por tenant + fila de pendentes por vencimento. */
    index("outbox_events_claim_idx").on(
      table.tenantId,
      table.status,
      table.availableAt,
      table.createdAt,
    ),
    check(
      "outbox_events_status_check",
      sql`${table.status} in ('pending', 'processing', 'processed', 'failed')`,
    ),
    check("outbox_events_attempts_check", sql`${table.attempts} >= 0`),
    check(
      "outbox_events_identity_check",
      sql`${table.eventType} <> '' and ${table.aggregateType} <> '' and ${table.aggregateId} <> '' and ${table.idempotencyKey} <> ''`,
    ),
  ],
);

/** Inbox do consumidor (23.2): a entrega é at-least-once, então a chave
 * (consumer, event) é o que garante 1 efeito por evento mesmo com reentrega. É
 * gravada na MESMA transação do efeito do handler. */
export const outboxConsumptions = pgTable(
  "outbox_consumptions",
  {
    consumerName: text("consumer_name").notNull(),
    eventId: uuid("event_id")
      .notNull()
      .references(() => outboxEvents.id, { onDelete: "cascade" }),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    consumedAt: timestamp("consumed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [primaryKey({ columns: [table.consumerName, table.eventId] })],
);

/** §28.2 — checkpoint do backfill: uma linha por TENTATIVA (`runKey`) do trabalho
 * lógico (`workKey`). `version` é o token do CAS: o store só grava quando a
 * versão persistida é exatamente a anterior, então dois runners no mesmo
 * `runKey` nunca se sobrescrevem em silêncio — o perdedor recebe conflito. */
export const backfillCheckpoints = pgTable(
  "backfill_checkpoints",
  {
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    runKey: text("run_key").notNull(),
    cursor: text("cursor"),
    completed: boolean("completed").notNull().default(false),
    batches: integer("batches").notNull().default(0),
    rowsScanned: integer("rows_scanned").notNull().default(0),
    rowsApplied: integer("rows_applied").notNull().default(0),
    rowsDuplicate: integer("rows_duplicate").notNull().default(0),
    errors: integer("errors").notNull().default(0),
    version: integer("version").notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.runKey] }),
    check("backfill_checkpoints_identity_check", sql`${table.runKey} <> ''`),
    check("backfill_checkpoints_version_check", sql`${table.version} >= 0`),
    check(
      "backfill_checkpoints_counters_check",
      sql`${table.batches} >= 0 and ${table.rowsScanned} >= 0 and ${table.rowsApplied} >= 0 and ${table.rowsDuplicate} >= 0 and ${table.errors} >= 0`,
    ),
  ],
);

/** §28.4 — marcador de idempotência: a chave é derivada da LINHA (não da
 * tentativa), então reexecutar o mesmo trabalho em outra tentativa não reaplica
 * o efeito. É gravado na MESMA transação do efeito (`applyWorkItemOnce`). */
export const backfillWorkItems = pgTable(
  "backfill_work_items",
  {
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    workKey: text("work_key").notNull(),
    runKey: text("run_key").notNull(),
    rowKey: text("row_key").notNull(),
    appliedAt: timestamp("applied_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.workKey] }),
    index("backfill_work_items_tenant_run_key_idx").on(table.tenantId, table.runKey),
    check(
      "backfill_work_items_identity_check",
      sql`${table.workKey} <> '' and ${table.rowKey} <> '' and ${table.runKey} <> ''`,
    ),
  ],
);

/** §43/§15.2 — memória persistente (alvo M-05, degrau D2). Os nomes são os do
 * plano (`ai_memories`/`ai_memory_sources`); `chat_*` permanece como
 * implementação vigente do §15.2-conversas (decisão A do STEWARD: alias
 * canônico, sem renomeação de tabela em uso). `(tenant_id, id)` é único para
 * servir de alvo da FK composta de `ai_memory_sources` — o padrão §34 de
 * `chat_conversations`/`chat_messages`.
 *
 * `user_id` é o autor da gravação (não o tenant): a FK composta para
 * `tenant_memberships` impede memória atribuída a quem não é membro e dá a
 * âncora por usuário que D4 exige para delete/export. `confidence` é a cópia de
 * retrieval da confiança declarada na proveniência (nula quando a policy não
 * exige proveniência e o candidato foi gravado sem fonte) e `importance` usa
 * `0` como neutro documentado — o read model `MemoryRecord.importance` é
 * numérico. */
export const aiMemories = pgTable(
  "ai_memories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    scope: text("scope").notNull(),
    content: text("content").notNull(),
    /** Chave determinística de dedup (§15.6/D3, SD-C3-1): sha256 hex de
     * `scope ‖ 0x1f ‖ discriminador ‖ 0x1f ‖ conteúdo normalizado`. O
     * discriminador impede que dois usuários com o mesmo texto colapsem numa
     * linha só; a normalização (NFC + trim + colapso de espaços internos) não
     * toca maiúsculas/minúsculas. */
    dedupKey: text("dedup_key").notNull(),
    /** Camada da memória (§15.2/§13): é ela que seleciona o TTL em
     * `ai_memory_policies`. `L2` (episódica) é o default **declarado** do
     * append atual (observações de conversa/tool); L0 não é persistido. */
    layer: text("layer").notNull().default("L2"),
    /** Fim da validade, derivado da policy da camada **na gravação** (`null` =
     * sem expiração: L4 acompanha a entidade referenciada e L5 é versionada).
     * É a coluna do expirador e o segundo filtro do retrieval (defesa em
     * profundidade enquanto o expirador não rodou). */
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    importance: doublePrecision("importance").notNull().default(0),
    confidence: doublePrecision("confidence"),
    status: text("status").notNull().default("active"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    /** Alvo da FK composta de `ai_memory_sources`: precisa ser **constraint**
     * (não índice) para existir antes dos `ALTER TABLE ... ADD FOREIGN KEY` do
     * arquivo gerado — mesmo padrão de `chat_conversations`. */
    unique("ai_memories_tenant_id_id_uidx").on(table.tenantId, table.id),
    /** Dedup do D3 (§15.6/SD-C3-2): **único parcial** — o mesmo conteúdo só
     * colide entre memórias **ativas** do mesmo tenant; uma memória substituída
     * (`status='superseded'`) não bloqueia a gravação de um ativo novo. É o
     * índice que resolve a concorrência do append (`ON CONFLICT … DO NOTHING`,
     * SD-C3-10, sem advisory lock). */
    uniqueIndex("ai_memories_tenant_dedup_key_active_uidx")
      .on(table.tenantId, table.dedupKey)
      .where(sql`${table.status} = 'active'`),
    /** Índice do retrieval lexical de D5/D6: tenant primeiro (§15.8). */
    index("ai_memories_tenant_status_created_idx").on(
      table.tenantId,
      table.status,
      table.createdAt,
    ),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("cascade"),
    check("ai_memories_scope_check", sql`${table.scope} in ('tenant', 'user', 'conversation')`),
    check("ai_memories_content_check", sql`${table.content} <> ''`),
    /** Vocabulário de estados do Apêndice C (§15.6/D4): `expired` entra com o
     * TTL. `deleted` **não** entra porque o delete é físico (a linha não existe
     * para carregar o estado — o rastro é a linha de `ai_memory_access_log`) e
     * `rejected` nunca é persistido (a policy de D1 recusa o candidato antes da
     * gravação). */
    check("ai_memories_status_check", sql`${table.status} in ('active', 'superseded', 'expired')`),
    check("ai_memories_layer_check", sql`${table.layer} in ('L1', 'L2', 'L3', 'L4', 'L5')`),
    check(
      "ai_memories_importance_check",
      sql`${table.importance} >= 0 and ${table.importance} <= 1`,
    ),
    check(
      "ai_memories_confidence_check",
      sql`${table.confidence} is null or (${table.confidence} >= 0 and ${table.confidence} <= 1)`,
    ),
  ],
);

/** §15.4 — proveniência 1:N de uma memória (decisão C do STEWARD): as origens
 * conhecidas viram FKs **opcionais** (FK composta com coluna nula não é
 * verificada — MATCH SIMPLE), em vez do `sourceId` polimórfico do contrato.
 * `source_ref` preserva o rótulo opaco do produtor quando existe; o CHECK
 * `origin_check` exige que ao menos uma origem identifique a fonte, senão a
 * linha seria proveniência decorativa. `ON DELETE cascade` nas origens: origem
 * removida não deixa referência pendurada; `(tenant_id, memory_id)` em cascata
 * garante que apagar a memória não deixa fonte órfã. */
export const aiMemorySources = pgTable(
  "ai_memory_sources",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    memoryId: uuid("memory_id").notNull(),
    sourceKind: text("source_kind").notNull(),
    sourceRef: text("source_ref"),
    conversationId: uuid("conversation_id"),
    messageId: uuid("message_id"),
    productId: uuid("product_id"),
    simulationId: uuid("simulation_id"),
    userId: text("user_id"),
    inferred: boolean("inferred").notNull().default(false),
    confidence: doublePrecision("confidence").notNull(),
    capturedAt: timestamp("captured_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("ai_memory_sources_tenant_memory_idx").on(table.tenantId, table.memoryId),
    foreignKey({
      columns: [table.tenantId, table.memoryId],
      foreignColumns: [aiMemories.tenantId, aiMemories.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.conversationId],
      foreignColumns: [chatConversations.tenantId, chatConversations.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.messageId],
      foreignColumns: [chatMessages.tenantId, chatMessages.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.productId],
      foreignColumns: [products.tenantId, products.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.simulationId],
      foreignColumns: [simulations.tenantId, simulations.id],
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("cascade"),
    check(
      "ai_memory_sources_kind_check",
      sql`${table.sourceKind} in ('user', 'tool', 'model', 'import')`,
    ),
    check(
      "ai_memory_sources_confidence_check",
      sql`${table.confidence} >= 0 and ${table.confidence} <= 1`,
    ),
    check(
      "ai_memory_sources_ref_check",
      sql`${table.sourceRef} is null or ${table.sourceRef} <> ''`,
    ),
    check(
      "ai_memory_sources_origin_check",
      sql`${table.sourceRef} is not null or ${table.conversationId} is not null or ${table.messageId} is not null or ${table.productId} is not null or ${table.simulationId} is not null or ${table.userId} is not null`,
    ),
  ],
);

/** §15.6/D3 — histórico imutável de uma memória (`ai_memory_versions`, SD-C3-3).
 *
 * A revisão arquiva o estado **substituído** antes de atualizar o head
 * (`ai_memories`) in-place: a linha gravada guarda `content`/`dedup_key` da
 * versão anterior, então o histórico inteiro é reconstruível (versões em ordem
 * de `version` + head). Nenhum `UPDATE`/`DELETE` é concedido a `app_runtime`
 * (SD-C3-4) — a imutabilidade é estrutural, não disciplina de código.
 *
 * A FK composta `(tenant_id, memory_id) → ai_memories(tenant_id, id)` é
 * **ON DELETE RESTRICT**: sem histórico, o delete do D2 continua valendo; com
 * histórico, o banco recusa a remoção do head e o expurgo passa a ser o caminho
 * explícito (SD-C3-9). */
export const aiMemoryVersions = pgTable(
  "ai_memory_versions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    memoryId: uuid("memory_id").notNull(),
    /** Índice do estado arquivado na memória (1, 2, …), nunca reutilizado. */
    version: integer("version").notNull(),
    content: text("content").notNull(),
    dedupKey: text("dedup_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    /** Alvo da FK composta de futuras tabelas e chave de leitura do histórico
     * (`listVersions` ordena por `version` dentro da memória). */
    unique("ai_memory_versions_tenant_memory_version_uidx").on(
      table.tenantId,
      table.memoryId,
      table.version,
    ),
    foreignKey({
      columns: [table.tenantId, table.memoryId],
      foreignColumns: [aiMemories.tenantId, aiMemories.id],
    }).onDelete("restrict"),
    check("ai_memory_versions_version_check", sql`${table.version} > 0`),
    check("ai_memory_versions_content_check", sql`${table.content} <> ''`),
  ],
);

/** §15.6/D3 — registro de conflito (`ai_memory_conflicts`, SD-C3-6).
 *
 * D3 **não** julga contradição semântica (SD-C3-5): o policy/service registra o
 * candidato contraditório com `recordConflict()` e o ativo **nunca** é
 * sobrescrito — esta tabela só acrescenta linhas, e o ciclo de vida
 * (`open → dismissed|resolved`) é do serviço. A FK composta também é
 * **ON DELETE RESTRICT**, pelo mesmo motivo do histórico. */
export const aiMemoryConflicts = pgTable(
  "ai_memory_conflicts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    memoryId: uuid("memory_id").notNull(),
    candidateContent: text("candidate_content").notNull(),
    candidateDedupKey: text("candidate_dedup_key").notNull(),
    status: text("status").notNull().default("open"),
    detectedAt: timestamp("detected_at", { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (table) => [
    index("ai_memory_conflicts_tenant_memory_idx").on(table.tenantId, table.memoryId),
    index("ai_memory_conflicts_tenant_status_idx").on(table.tenantId, table.status),
    foreignKey({
      columns: [table.tenantId, table.memoryId],
      foreignColumns: [aiMemories.tenantId, aiMemories.id],
    }).onDelete("restrict"),
    check(
      "ai_memory_conflicts_status_check",
      sql`${table.status} in ('open', 'dismissed', 'resolved')`,
    ),
    check("ai_memory_conflicts_content_check", sql`${table.candidateContent} <> ''`),
  ],
);

/** §15.1/L5 + §15.4 — política de retenção **versionada** por camada
 * (`ai_memory_policies`, SD-D4-A/H-12). Tabela **global** (não há `tenant_id`:
 * retenção é política do sistema, não do tenant) e **append-only por
 * privilégio**: `app_runtime` recebe `SELECT`+`INSERT` — publicar uma política
 * nova é um INSERT (versão maior), nunca um UPDATE; reverter é publicar de novo
 * a versão anterior. O backend lê `max(version)` por camada, então **nenhum TTL
 * vive em constante de código nem em SQL**: os valores são linhas (defaults
 * aprovados no H-12: L1 30 d · L2 180 d · L3 365 d · L4 acompanha a entidade
 * referenciada · L5 sem TTL, ambos `null`). */
export const aiMemoryPolicies = pgTable(
  "ai_memory_policies",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    layer: text("layer").notNull(),
    version: integer("version").notNull(),
    /** Segundos até a expiração; `null` = retenção indefinida. */
    ttlSeconds: integer("ttl_seconds"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    unique("ai_memory_policies_layer_version_uidx").on(table.layer, table.version),
    check("ai_memory_policies_layer_check", sql`${table.layer} in ('L1', 'L2', 'L3', 'L4', 'L5')`),
    check("ai_memory_policies_version_check", sql`${table.version} > 0`),
    check(
      "ai_memory_policies_ttl_check",
      sql`${table.ttlSeconds} is null or ${table.ttlSeconds} > 0`,
    ),
  ],
);

/** §43/§15.4 — trilha de auditoria da memória (`ai_memory_access_log`, D4):
 * registra **acesso, delete e export** com quem (`user_id`), quando
 * (`created_at`), o quê (`action`, `memory_id`, `row_count`) e o resultado.
 *
 * Sem `content` e sem o texto da consulta por desenho (o log não é superfície
 * de dado pessoal — o gap report exige "nenhuma linha contém content"). Sem FK
 * para `ai_memories`: a trilha tem de **sobreviver** ao delete físico que ela
 * audita (uma FK em cascata apagaria o próprio rastro; `RESTRICT` impediria o
 * delete). A âncora de tenant é a FK composta para `tenant_memberships`, no
 * molde de `audit_events` (`0000:274`), e a role de runtime recebe
 * `SELECT`+`INSERT` — sem `UPDATE`/`DELETE`, a imutabilidade da trilha é
 * privilégio, não disciplina de código. */
export const aiMemoryAccessLog = pgTable(
  "ai_memory_access_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ...tenantIdentity,
    action: text("action").notNull(),
    /** Alvo único (delete); `null` em operação de conjunto (access/export). */
    memoryId: uuid("memory_id"),
    result: text("result").notNull(),
    /** Linhas afetadas/devolvidas: 1 no delete efetivo, N no access/export. */
    rowCount: integer("row_count").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("ai_memory_access_log_tenant_action_created_idx").on(
      table.tenantId,
      table.action,
      table.createdAt,
    ),
    index("ai_memory_access_log_tenant_memory_idx").on(table.tenantId, table.memoryId),
    foreignKey({
      columns: [table.tenantId, table.userId],
      foreignColumns: [tenantMemberships.tenantId, tenantMemberships.userId],
    }).onDelete("restrict"),
    check(
      "ai_memory_access_log_action_check",
      sql`${table.action} in ('access', 'delete', 'export')`,
    ),
    check(
      "ai_memory_access_log_result_check",
      sql`${table.result} in ('allowed', 'not_found', 'refused')`,
    ),
    check("ai_memory_access_log_row_count_check", sql`${table.rowCount} >= 0`),
  ],
);

export type User = typeof users.$inferSelect;
export type Tenant = typeof tenants.$inferSelect;
export type TenantMembership = typeof tenantMemberships.$inferSelect;
export type Product = typeof products.$inferSelect;
export type Expense = typeof expenses.$inferSelect;
export type PurchasePriceHistory = typeof purchasePriceHistory.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type SaleItem = typeof salesItems.$inferSelect;
export type Simulation = typeof simulations.$inferSelect;
export type CalculationSnapshot = typeof calculationSnapshots.$inferSelect;
export type OutboxEvent = typeof outboxEvents.$inferSelect;
export type OutboxConsumption = typeof outboxConsumptions.$inferSelect;
export type BackfillCheckpointRecord = typeof backfillCheckpoints.$inferSelect;
export type BackfillWorkItem = typeof backfillWorkItems.$inferSelect;
export type AiMemory = typeof aiMemories.$inferSelect;
export type AiMemorySource = typeof aiMemorySources.$inferSelect;
export type AiMemoryVersion = typeof aiMemoryVersions.$inferSelect;
export type AiMemoryConflict = typeof aiMemoryConflicts.$inferSelect;
export type AiMemoryPolicy = typeof aiMemoryPolicies.$inferSelect;
export type AiMemoryAccessLog = typeof aiMemoryAccessLog.$inferSelect;
