/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNovoProdutoRouteImport } from './routes/_authenticated/novo-produto'
import { Route as AuthenticatedPontoEquilibrioRouteImport } from './routes/_authenticated/ponto-equilibrio'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedSimulacoesRouteImport } from './routes/_authenticated/simulacoes'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report'
import { Route as ApiVitalsRouteImport } from './routes/api/vitals'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoProdutoRoute =
  AuthenticatedNovoProdutoRouteImport.update({
    id: '/novo-produto',
    path: '/novo-produto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPontoEquilibrioRoute =
  AuthenticatedPontoEquilibrioRouteImport.update({
    id: '/ponto-equilibrio',
    path: '/ponto-equilibrio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulacoesRoute = AuthenticatedSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVitalsRoute = ApiVitalsRouteImport.update({
  id: '/api/vitals',
  path: '/api/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/novo-produto': typeof AuthenticatedNovoProdutoRoute
  '/ponto-equilibrio': typeof AuthenticatedPontoEquilibrioRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/simulacoes': typeof AuthenticatedSimulacoesRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/vitals': typeof ApiVitalsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/novo-produto': typeof AuthenticatedNovoProdutoRoute
  '/ponto-equilibrio': typeof AuthenticatedPontoEquilibrioRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/simulacoes': typeof AuthenticatedSimulacoesRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/vitals': typeof ApiVitalsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/novo-produto': typeof AuthenticatedNovoProdutoRoute
  '/_authenticated/ponto-equilibrio': typeof AuthenticatedPontoEquilibrioRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/simulacoes': typeof AuthenticatedSimulacoesRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/vitals': typeof ApiVitalsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/despesas'
    | '/diagnostico'
    | '/inicio'
    | '/novo-produto'
    | '/ponto-equilibrio'
    | '/precos'
    | '/produtos'
    | '/simulacoes'
    | '/vendas'
    | '/api/csp-report'
    | '/api/vitals'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/despesas'
    | '/diagnostico'
    | '/inicio'
    | '/novo-produto'
    | '/ponto-equilibrio'
    | '/precos'
    | '/produtos'
    | '/simulacoes'
    | '/vendas'
    | '/api/csp-report'
    | '/api/vitals'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/despesas'
    | '/_authenticated/diagnostico'
    | '/_authenticated/inicio'
    | '/_authenticated/novo-produto'
    | '/_authenticated/ponto-equilibrio'
    | '/_authenticated/precos'
    | '/_authenticated/produtos'
    | '/_authenticated/simulacoes'
    | '/_authenticated/vendas'
    | '/api/csp-report'
    | '/api/vitals'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  ApiVitalsRoute: typeof ApiVitalsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-produto': {
      id: '/_authenticated/novo-produto'
      path: '/novo-produto'
      fullPath: '/novo-produto'
      preLoaderRoute: typeof AuthenticatedNovoProdutoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto-equilibrio': {
      id: '/_authenticated/ponto-equilibrio'
      path: '/ponto-equilibrio'
      fullPath: '/ponto-equilibrio'
      preLoaderRoute: typeof AuthenticatedPontoEquilibrioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulacoes': {
      id: '/_authenticated/simulacoes'
      path: '/simulacoes'
      fullPath: '/simulacoes'
      preLoaderRoute: typeof AuthenticatedSimulacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vitals': {
      id: '/api/vitals'
      path: '/api/vitals'
      fullPath: '/api/vitals'
      preLoaderRoute: typeof ApiVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNovoProdutoRoute: typeof AuthenticatedNovoProdutoRoute
  AuthenticatedPontoEquilibrioRoute: typeof AuthenticatedPontoEquilibrioRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedSimulacoesRoute: typeof AuthenticatedSimulacoesRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNovoProdutoRoute: AuthenticatedNovoProdutoRoute,
  AuthenticatedPontoEquilibrioRoute: AuthenticatedPontoEquilibrioRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedSimulacoesRoute: AuthenticatedSimulacoesRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  ApiVitalsRoute: ApiVitalsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
